### ISSUE TITLE
Mockup interfaccia

### ISSUE THREAD

**Issue by mceserani** [mceserani/React_2024_Lista_della_spesa#1]
Mockup dell'interfaccia grafica.

**Comment by mceserani** [comment]
![Image](https://github.com/mceserani/React_2024_Lista_della_spesa/assets/18749673/989a6aa9-2806-4965-b853-58b38fc5d97b)

**Comment by Wistytomb** [comment]
![mockup](https://github.com/mceserani/React_2024_Lista_della_spesa/assets/124425991/2cec110d-48dd-4b16-8a89-0195e0a70d12)
![mockup_2](https://github.com/mceserani/React_2024_Lista_della_spesa/assets/124425991/95b0e7d0-e276-4537-ade7-27bf3d084f85)

**Comment by Enea006** [comment]
![estps (1)](https://github.com/mceserani/React_2024_Lista_della_spesa/assets/123799507/6a4be63f-bec8-4132-98ea-d8b8b139c832)

Versione scura.
