### ISSUE TITLE
Studio sulla possibilità di salvare le liste della spesa utilizzando LocalStorage

### ISSUE THREAD

**Issue by mceserani** [mceserani/React_2024_Lista_della_spesa#10]
Studio sulla possibilità di salvare le liste della spesa utilizzando LocalStorage

**Comment by Fabianski12** [comment]
[Salvataggio della Liste della Spesa con LocalStorage.docx](https://github.com/mceserani/React_2024_Lista_della_spesa/files/15442639/Salvataggio.della.Liste.della.Spesa.con.LocalStorage.docx)
