### ISSUE TITLE
Funzionalità

### ISSUE THREAD

**Issue by mceserani** [mceserani/React_2024_Lista_della_spesa#2]
Descrizione completa delle funzionalità.

**Comment by fabio3107** [comment]
[Documento funzionalità lista della spesa.docx](https://github.com/mceserani/React_2024_Lista_della_spesa/files/15414153/Documento.funzionalita.lista.della.spesa.docx)

**Comment by Fabianski12** [comment]
[Documento funzionalità lista della spesa.docx](https://github.com/mceserani/React_2024_Lista_della_spesa/files/15414344/Documento.funzionalita.lista.della.spesa.docx)

**Comment by mceserani** [comment]
1. Manca il componente Header
2. Approfondire la persistenza dei dati
- Come si usa LocalStorage?
- Che caratteristiche deve avere un backend? Che tecnologia utilizzerebbe?

**Comment by DinaLevrai** [comment]
Prof abbiamo aggiunto le cose che mancavano
[Documento funzionalità lista della spesa.docx](https://github.com/mceserani/React_2024_Lista_della_spesa/files/15420613/Documento.funzionalita.lista.della.spesa.docx)
