### ISSUE TITLE
Studio sulla possibilità di salvare le liste della spesa su un server

### ISSUE THREAD

**Issue by mceserani** [mceserani/React_2024_Lista_della_spesa#9]
Studio sulla possibilità di salvare le liste della spesa su un server

**Comment by Vince778** [comment]
[salvare liste della spesa su un server.pdf](https://github.com/mceserani/React_2024_Lista_della_spesa/files/15442678/salvare.liste.della.spesa.su.un.server.pdf)

**Comment by mceserani** [comment]
Aggiungere un elenco degli endpoint

**Comment by Vince778** [comment]
[salvare liste della spesa su un server (1).pdf](https://github.com/mceserani/React_2024_Lista_della_spesa/files/15496407/salvare.liste.della.spesa.su.un.server.1.pdf)
